# Generated by Django 4.2.2 on 2023-06-19 09:02

import django.core.validators
from django.db import migrations, models
import myplant_app.myplant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(choices=[('OUTDOOR', 'Outdoor Plants'), ('INDOOR', 'Indoor Plants')], max_length=14)),
                ('name', models.CharField(max_length=20, validators=[myplant_app.myplant.models.validate_plant_name, django.core.validators.MinLengthValidator(2)])),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[myplant_app.myplant.models.validate_first_letter])),
                ('last_name', models.CharField(max_length=20, validators=[myplant_app.myplant.models.validate_first_letter])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
