# Generated by Django 4.2.1 on 2023-05-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(default=19, max_length=15),
            preserve_default=False,
        ),
    ]
