# Generated by Django 4.2.1 on 2023-05-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_nullblankdemo_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.URLField(blank=True, default='default-picture-url'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
