# Generated by Django 4.2.1 on 2023-06-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_employee_options_project_created_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
