# Generated by Django 4.2.1 on 2023-06-02 18:00
from django.utils.text import slugify

from django.db import migrations

def add_slugs(apps, schema_editor):
    # cant import Department here, because it would be imported from
    # model_demo/web/models.py, which is notthe same as the current models.py
    Department = apps.get_model('web', 'Department')
    departments = Department.objects.all()
    for department in departments: # QuerySet
        department.slug = slugify(department.name)
        # department.slug = department.name.lower().replace(' ', '-')
    Department.objects.bulk_update(departments, ['slug'])
    # department.save()

def remove_slugs(apps, schema_editor):
    Department = apps.get_model('web', 'Department')
    departments = Department.objects.all()
    for department in departments: # QuerySet
        department.slug = None
    Department.objects.bulk_update(departments, ['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_department_slug'),
    ]

    operations = [
        migrations.RunPython(add_slugs, remove_slugs),
    ]
