# Generated by Django 4.2.3 on 2023-08-16 06:58

import django.core.validators
from django.db import migrations, models
import softuni_exam.web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('category', models.CharField(choices=[('SPORTS', 'Sports'), ('FESTIVALS', 'Festivals'), ('CONFERENCES', 'Conferences'), ('PERFORMING_ART', 'Performing Art'), ('CONCERTS', 'Concerts'), ('THEME_PARTY', 'Theme Party'), ('OTHER', 'Other')])),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(validators=[softuni_exam.web.models.validate_date])),
                ('event_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[softuni_exam.web.models.validate_first_name])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4)])),
                ('email', models.EmailField(max_length=45)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5), softuni_exam.web.models.validate_password])),
            ],
        ),
    ]
